# aims
   - correct the BCR cell barocode using scRNAseq cell barcode as whitelist (allowing 1 mismatch)

# INPUT DATA 
#   - sc data with singleR infor
#   - consensus BCR from TRUST4 output 




# load library

```{r}
suppressPackageStartupMessages({

  library(ggplot2)
  library(tidyverse)
  library(Seurat)
  library(RecordLinkage)
  source("/home/hohu/Desktop/LinSeq/script/BcrPreprocessFunction.R")

})
```



  

##==============================================================================##
#    MAIN FUNCTION-1: LV correction for heavy chain 
##==============================================================================##

global variable
```{r}

inputPath_TRUST4Bcr<-"/media/hohu/ArmorATD1/TRUST4_output/"
inputPath_Bcr<-"/media/hohu/ArmorATD1/snakemake/covid_top20_bcr_snakemake/results/summary/pip4/step6/" # acctually results from pip5
inputPath_Gex<- "/home/hohu/Desktop/covid_top20_bcr_snakemake/data/from_xiaoli/singleR/rename/"

outputPath_summary <- "/home/hohu/Desktop/LinSeq/result/summary/no4/"
ifelse(!dir.exists(outputPath_summary), dir.create(outputPath_summary, recursive = T),FALSE)

outputPath_plot <- "/home/hohu/Desktop/LinSeq/result/plot/no4/"
ifelse(!dir.exists(outputPath_plot), dir.create(outputPath_plot, recursive = T),FALSE)

```

 
# Main 
 
 
```{r}
fileList <- c("HD960","HD1500","HD3600","p36T1","p36T2","p36T4" )


lv1_bcrHeavy<- lv_repairBcrHeavy( file_List=fileList,df_igblastBcrPath=inputPath_Bcr, 
                                   df_TRUST4BcrPath=inputPath_TRUST4Bcr, df_scRdsPath=inputPath_Gex,outputPathPlot=outputPath_plot,
                                   outputPathSummary=outputPath_summary)
  
sapply(lv1_bcrHeavy,dim)

 
```

  

##==============================================================================##
#    MAIN FUNCTION-2: LV correction for light chain 
##==============================================================================##
 
# Main 
 
```{r}

fileList <- c("HD960","HD1500","HD3600","p36T1","p36T2","p36T4")


# lv distance =1 
lv1_bcrLight<- lv_repairBcrLight( file_List=fileList,df_igblastBcrPath=inputPath_Bcr,  
                                 df_TRUST4BcrPath=inputPath_TRUST4Bcr, df_scRdsPath=inputPath_Gex,outputPathPlot=outputPath_plot,
                                 outputPathSummary=outputPath_summary )

sapply(lv1_bcrLight,dim)


 


```


 
# print session infor
```{r}
sessionInfo()
```





