
# aims
   - plot the percentage of sc with matched heavy and light chain 


# Note
- The source path for "BcrPreprocessFunction.R" need to be changed with your local path
- All the input and out path need to be changed to your local path 

# load library

```{r}

suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(scales))
suppressPackageStartupMessages(library(dplyr))
source("/home/hohu/Desktop/LinkSeq1/script/Preprocess/BcrPreprocessFunction.R")
 

```


# global variable

```{r}
#  pre-processed BCR (consensus collapsed,lv1 corrected ) as input
file_pathBcr<-  "/home/hohu/Desktop/LinkSeq1/data/bcr_lv1/"  # with all preprocessed bcr data

# file_pathBcr<- "/home/hohu/Desktop/LinkSeq1/result/" # with example run: HD960 bcr data

# scRNAseq RDS file (removed empty/low quality cells) 
file_pathGex <- "/home/hohu/Desktop/LinkSeq1/data/sc/"

output_path <- "/home/hohu/Desktop/LinkSeq1/result/"
ifelse(!dir.exists(output_path), dir.create(output_path, recursive = T),FALSE)
output_summary <- "/home/hohu/Desktop/LinkSeq1/result/"
ifelse(!dir.exists(output_summary), dir.create(output_summary, recursive = T),FALSE)

```


# MAIN 

```{r}

fileList<- c("HD2B1500","HD2B3600","HD2B960","p36T1","p36T2","p36T4")
# example test run: fileList<- c("HD2B960")
summary_scBcr <- summary_scMatchToBcrHL(df_fileList=fileList,df_bcrInputPath=file_pathBcr,
                                        rdsInputPath=file_pathGex,outputPath=output_path,outputSummary=output_summary)

```




# print session infor
```{r}
sessionInfo()
```



